name: CI

on:
  push:
    branches:
      - 'main'
      - 'master'
      - 'v*'
    tags:
      - v*
  pull_request:
  workflow_dispatch:
  repository_dispatch:
    types: [run_build]


jobs:
  build:
    strategy:
     matrix:
       toolchain: ["windows-static-x86","linux-x86"]
    runs-on: ubuntu-latest
    container: dockcross/${{ matrix.toolchain }}:latest
    steps:

    - uses: actions/checkout@v2
    - run: |
        sudo apt-get install --assume-yes p7zip-full 
        git fetch --prune --unshallow
        
    - name: Compile project
      run: |
        DATEE=`date '+[%Y-%m-%d]'`
        mv LICENSE LICENSE.TXT
        mkdir build
        cd build
        cmake .. -DCMAKE_BUILD_TYPE=Release
        make clean all
        7z a -t7z ${{ github.event.repository.name }}-${{ matrix.toolchain }}.7z ../Changes.Log ../LICENSE.TXT ../README.md "${{ github.event.repository.name }}*"
        ls -r
        
    - name: Upload artifacts
      if: ${{ success() }}
      uses: actions/upload-artifact@v2
      with:
        name: ${{ github.event.repository.name }}-${{ matrix.toolchain }}
        path: |
             build/${{ github.event.repository.name }}-${{ matrix.toolchain }}.7z
             
    - name: Deploy pre-release
      uses: softprops/action-gh-release@v1
      if: (github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main')
      with:
        token: "${{ secrets.GITHUB_TOKEN }}"
        fail_on_unmatched_files: true
        name: "Latest build"
        tag_name: "Latest"
        prerelease: true
        files: |
            build/${{ github.event.repository.name }}-${{ matrix.toolchain }}.7z
